services:
  - type: web
    name: ğš«ğš´ğƒğš©ğš«ğƒ-ğš³ğƒ-ğ›2
    env: node
    plan: free
    repo: https://github.com/Mrandbad/ANDBAD-MD-V2
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false

